import { Router } from 'express';
import { query, transaction } from '../../config/db.js';
import { authenticate, requirePermission } from '../../middleware/auth.js';
import { asyncHandler } from '../../utils/asyncHandler.js';
const router = Router();
export const vehiculosRouter = router;
router.use(authenticate);
const tipos = ['AUTOMOVIL','CAMIONETA','MOTOCICLETA','CAMION','MINIBUS','OTRO'];
const categorias = ['MILITAR','CIVIL','ADMINISTRATIVO','ESTUDIANTE','VISITANTE','PROVEEDOR','INSTITUCIONAL'];
const estados = ['ACTIVO','SUSPENDIDO','RETIRADO'];
const autorizaciones = ['PERMANENTE','TEMPORAL','EXCEPCIONAL'];
const uuid = x => /^[0-9a-f]{8}-[0-9a-f]{4}-[1-8][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i.test(x||'');
const texto = (v,max=170) => String(v??'').trim().slice(0,max);
const placa = v => texto(v,20).toUpperCase().replace(/[\s-]/g,'');
function bad(res,message){return res.status(400).json({message});}
async function auditar(c,req,accion,entidad,id,detalle){await c.query(`INSERT INTO auditoria(usuario_id,accion,entidad,entidad_id,detalle,direccion_ip,agente_usuario) VALUES($1,$2,$3,$4,$5,$6,$7)`,[req.user.sub,accion,entidad,id,JSON.stringify(detalle),req.ip,req.headers['user-agent']||null]);}
function datosVehiculo(b){return {placa:placa(b.placa),tipo: texto(b.tipoVehiculo||'AUTOMOVIL',40),marca:texto(b.marca,80)||null,modelo:texto(b.modelo,80)||null,color:texto(b.color,60)||null,referencia:texto(b.referenciaPropietario,170)||null,categoria:texto(b.categoriaUsuario||'INSTITUCIONAL',40),estado:texto(b.estado||'ACTIVO',20)};}
function validarVehiculo(v){if(!/^[A-Z0-9]{4,12}$/.test(v.placa))return 'La placa debe tener entre 4 y 12 caracteres alfanuméricos.';if(!tipos.includes(v.tipo))return 'Tipo de vehículo inválido.';if(!categorias.includes(v.categoria))return 'Categoría inválida.';if(!estados.includes(v.estado))return 'Estado inválido.';return null;}
function imagen(v){return typeof v==='string' && /^data:image\/(jpeg|png|webp);base64,[A-Za-z0-9+/=]+$/.test(v) && v.length <= 1800000 ? v : null;}
async function validarPropietario(c,id){if(!uuid(id))return false;const q=await c.query('SELECT 1 FROM usuarios WHERE id=$1 AND estado=\'ACTIVO\'',[id]);return q.rowCount>0;}
router.get('/propietarios/opciones',requirePermission('vehiculos.ver'),asyncHandler(async(req,res)=>{const r=await query(`SELECT id,nombre_completo,nombre_usuario FROM usuarios WHERE estado='ACTIVO' ORDER BY nombre_completo LIMIT 500`);res.json(r.rows)}));
router.get('/:id/fotografias',requirePermission('vehiculos.ver'),asyncHandler(async(req,res)=>{if(!uuid(req.params.id))return bad(res,'Identificador inválido');const r=await query('SELECT foto_vehiculo,foto_placa FROM vehiculos WHERE id=$1',[req.params.id]);if(!r.rowCount)return res.status(404).json({message:'No encontrado'});res.json(r.rows[0])}));
function datosAutorizacion(b){return {tipo:texto(b.tipoAutorizacion,30),desde:b.validoDesde||new Date().toISOString(),hasta:b.validoHasta||null,motivo:texto(b.motivo,1000)||null};}
function validarAutorizacion(a){if(!autorizaciones.includes(a.tipo))return 'Seleccione autorización permanente, temporal o excepcional.';const ini=Date.parse(a.desde),fin=a.hasta?Date.parse(a.hasta):null;if(!Number.isFinite(ini)||a.hasta&&!Number.isFinite(fin))return 'Fechas inválidas.';if(a.tipo!=='PERMANENTE'&&!a.hasta)return 'Las autorizaciones temporales y excepcionales requieren fecha de fin.';if(fin!==null&&fin<=ini)return 'La fecha final debe ser posterior al inicio.';if(a.tipo==='EXCEPCIONAL'&&!a.motivo)return 'La autorización excepcional requiere motivo.';return null;}
router.get('/',requirePermission('vehiculos.ver'),asyncHandler(async(req,res)=>{
const q=texto(req.query.q,30),estado=texto(req.query.estado,20),categoria=texto(req.query.categoria,40);
if(estado&&!estados.includes(estado))return bad(res,'Estado de búsqueda inválido.');if(categoria&&!categorias.includes(categoria))return bad(res,'Categoría de búsqueda inválida.');
const r=await query(`SELECT v.id,v.placa,v.tipo_vehiculo,v.marca,v.modelo,v.color,v.referencia_propietario,v.categoria_usuario,v.estado,v.creado_en, u.nombre_completo propietario_nombre, v.propietario_usuario_id, (v.foto_vehiculo IS NOT NULL) tiene_foto_vehiculo,(v.foto_placa IS NOT NULL) tiene_foto_placa,a.id autorizacion_id,a.tipo_autorizacion,a.valido_desde,a.valido_hasta,a.estado autorizacion_estado, CASE WHEN a.id IS NULL THEN 'SIN_AUTORIZACION' WHEN a.estado='ACTIVA' AND a.valido_desde>NOW() THEN 'PENDIENTE' WHEN a.estado='ACTIVA' AND a.valido_hasta IS NOT NULL AND a.valido_hasta<NOW() THEN 'VENCIDA' ELSE a.estado END autorizacion_vigencia FROM vehiculos v LEFT JOIN usuarios u ON u.id=v.propietario_usuario_id LEFT JOIN LATERAL(SELECT * FROM autorizaciones_vehiculares x WHERE x.vehiculo_id=v.id ORDER BY x.creado_en DESC,x.id DESC LIMIT 1)a ON TRUE WHERE($1='' OR v.placa ILIKE '%'||$1||'%' ESCAPE '\\') AND($2='' OR v.estado=$2) AND($3='' OR v.categoria_usuario=$3) ORDER BY v.creado_en DESC LIMIT 500`,[q.replace(/[\%_]/g,'\$&'),estado,categoria]);res.json(r.rows);
}));
router.get('/:id/autorizaciones',requirePermission('vehiculos.ver'),asyncHandler(async(req,res)=>{if(!uuid(req.params.id))return bad(res,'Identificador inválido.');const r=await query(`SELECT a.id,a.vehiculo_id,a.tipo_autorizacion,a.valido_desde,a.valido_hasta,a.motivo,a.estado,a.creado_en, CASE WHEN a.estado='ACTIVA' AND a.valido_hasta<NOW() THEN 'VENCIDA' WHEN a.estado='ACTIVA' AND a.valido_desde>NOW() THEN 'PENDIENTE' ELSE a.estado END vigencia FROM autorizaciones_vehiculares a WHERE a.vehiculo_id=$1 ORDER BY a.creado_en DESC,a.id DESC`,[req.params.id]);res.json(r.rows)}));
router.post('/',requirePermission('vehiculos.gestionar'),asyncHandler(async(req,res)=>{const v=datosVehiculo(req.body||{}),e=validarVehiculo(v);if(e)return bad(res,e);const owner=req.body?.propietarioUsuarioId,fotoAuto=imagen(req.body?.fotoVehiculo),fotoPlaca=imagen(req.body?.fotoPlaca);if(!fotoAuto||!fotoPlaca)return bad(res,'Adjunte las fotografías del vehículo y de la placa, en JPG, PNG o WebP (máximo 1,3 MB por archivo).');if(!uuid(owner))return bad(res,'Seleccione el propietario registrado.');const row=await transaction(async c=>{if(!await validarPropietario(c,owner)){const er=new Error('El propietario no está habilitado.');er.status=400;throw er;}const r=await c.query(`INSERT INTO vehiculos(placa,tipo_vehiculo,marca,modelo,color,referencia_propietario,categoria_usuario,estado,creado_por,propietario_usuario_id,foto_vehiculo,foto_placa) VALUES($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING id,placa,propietario_usuario_id`,[v.placa,v.tipo,v.marca,v.modelo,v.color,v.referencia,v.categoria,v.estado,req.user.sub,owner,fotoAuto,fotoPlaca]);await auditar(c,req,'VEHICULO_CREAR','vehiculos',r.rows[0].id,{nuevo:v});return r.rows[0]});res.status(201).json(row)}));
router.patch('/:id',requirePermission('vehiculos.gestionar'),asyncHandler(async(req,res)=>{if(!uuid(req.params.id))return bad(res,'Identificador inválido.');const r=await transaction(async c=>{const old=await c.query('SELECT * FROM vehiculos WHERE id=$1 FOR UPDATE',[req.params.id]);if(!old.rowCount)return null;const previous=old.rows[0],b=req.body||{};const v=datosVehiculo({placa:b.placa??previous.placa,tipoVehiculo:b.tipoVehiculo??previous.tipo_vehiculo,marca:b.marca??previous.marca,modelo:b.modelo??previous.modelo,color:b.color??previous.color,referenciaPropietario:b.referenciaPropietario??previous.referencia_propietario,categoriaUsuario:b.categoriaUsuario??previous.categoria_usuario,estado:b.estado??previous.estado});const owner=b.propietarioUsuarioId??previous.propietario_usuario_id;const fotoAuto=b.fotoVehiculo===undefined?previous.foto_vehiculo:imagen(b.fotoVehiculo);const fotoPlaca=b.fotoPlaca===undefined?previous.foto_placa:imagen(b.fotoPlaca);if(!uuid(owner)||!fotoAuto||!fotoPlaca||!await validarPropietario(c,owner)){const err=new Error('Se requiere propietario activo y ambas fotografías válidas.');err.status=400;throw err;}const e=validarVehiculo(v);if(e){const err=new Error(e);err.status=400;throw err;}const up=await c.query(`UPDATE vehiculos SET placa=$2,tipo_vehiculo=$3,marca=$4,modelo=$5,color=$6,referencia_propietario=$7,categoria_usuario=$8,estado=$9,propietario_usuario_id=$10,foto_vehiculo=$11,foto_placa=$12 WHERE id=$1 RETURNING id,placa,propietario_usuario_id`,[req.params.id,v.placa,v.tipo,v.marca,v.modelo,v.color,v.referencia,v.categoria,v.estado,owner,fotoAuto,fotoPlaca]);await auditar(c,req,'VEHICULO_ACTUALIZAR','vehiculos',req.params.id,{anterior:{placa:previous.placa,estado:previous.estado,categoria:previous.categoria_usuario},nuevo:v});return up.rows[0]});if(!r)return res.status(404).json({message:'Vehículo no encontrado.'});res.json(r)}));
router.post('/:id/autorizaciones',requirePermission('vehiculos.gestionar'),asyncHandler(async(req,res)=>{if(!uuid(req.params.id))return bad(res,'Identificador inválido.');const a=datosAutorizacion(req.body||{}),e=validarAutorizacion(a);if(e)return bad(res,e);const result=await transaction(async c=>{const v=await c.query('SELECT * FROM vehiculos WHERE id=$1 FOR UPDATE',[req.params.id]);if(!v.rowCount){const er=new Error('Vehículo no encontrado.');er.status=404;throw er;}if(v.rows[0].estado!=='ACTIVO'){const er=new Error('Sólo se autorizan vehículos activos.');er.status=409;throw er;}const overlaps=await c.query(`SELECT id FROM autorizaciones_vehiculares WHERE vehiculo_id=$1 AND estado='ACTIVA' AND tstzrange(valido_desde,COALESCE(valido_hasta,'infinity'::timestamptz),'[)') && tstzrange($2::timestamptz,COALESCE($3::timestamptz,'infinity'::timestamptz),'[)') LIMIT 1`,[req.params.id,a.desde,a.hasta]);if(overlaps.rowCount){const er=new Error('Ya existe una autorización activa en ese intervalo. Suspenda o revoque la anterior.');er.status=409;throw er;}const r=await c.query(`INSERT INTO autorizaciones_vehiculares(vehiculo_id,tipo_autorizacion,valido_desde,valido_hasta,motivo,estado,autorizado_por) VALUES($1,$2,$3,$4,$5,'ACTIVA',$6) RETURNING *`,[req.params.id,a.tipo,a.desde,a.hasta,a.motivo,req.user.sub]);await auditar(c,req,'AUTORIZACION_CREAR','autorizaciones_vehiculares',r.rows[0].id,{vehiculo:req.params.id,nuevo:a});return r.rows[0]});res.status(201).json(result)}));
router.patch('/:id/autorizaciones/:aid',requirePermission('vehiculos.gestionar'),asyncHandler(async(req,res)=>{if(!uuid(req.params.id)||!uuid(req.params.aid))return bad(res,'Identificador inválido.');const estado=texto(req.body?.estado,20);if(!['SUSPENDIDA','REVOCADA'].includes(estado))return bad(res,'Sólo puede suspender o revocar una autorización.');const motivo=texto(req.body?.motivo,1000);if(!motivo)return bad(res,'Indique el motivo de la modificación.');const row=await transaction(async c=>{const found=await c.query(`SELECT * FROM autorizaciones_vehiculares WHERE id=$1 AND vehiculo_id=$2 FOR UPDATE`,[req.params.aid,req.params.id]);if(!found.rowCount)return null;if(found.rows[0].estado!=='ACTIVA'){const er=new Error('La autorización ya no está activa.');er.status=409;throw er;}const r=await c.query(`UPDATE autorizaciones_vehiculares SET estado=$2,motivo=CONCAT_WS(' | ',NULLIF(motivo,''),$3) WHERE id=$1 RETURNING *`,[req.params.aid,estado,`Cambio: ${motivo}`]);await auditar(c,req,'AUTORIZACION_'+estado,'autorizaciones_vehiculares',req.params.aid,{vehiculo:req.params.id,anterior:found.rows[0].estado,nuevo:estado,motivo});return r.rows[0]});if(!row)return res.status(404).json({message:'Autorización no encontrada.'});res.json(row)}));
