import {api,fecha,aviso,tienePermiso} from '../api.js';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function renderAccesos(c){
 const gestionar=tienePermiso('acceso.validar');
 c.innerHTML=`<div class="page-head"><div><h1>Control de ingreso y salida por placa</h1><p>Lectura OCR y verificación de autorizaciones.</p></div></div>${gestionar?`<section class="card panel"><h2>Capturar evidencia</h2><form id="lectura"><label>Movimiento<select name="tipoEvento"><option value="INGRESO">Ingreso</option><option value="SALIDA">Salida</option></select></label><label>Punto de acceso<input name="puntoAcceso" value="PORTERIA" maxlength="120" required></label><label>Imagen real de la placa (foto o cámara del dispositivo)<input type="file" name="imagen" accept="image/*" capture="environment" required></label><p><button class="btn primary">Reconocer y registrar</button></p></form><div id="resultadoLectura" aria-live="polite"></div></section>`:''}<section class="card panel"><h2>Eventos registrados</h2><div id="historialLecturas"></div></section>`;
 async function refrescar(){try{const d=await api('/accesos/eventos');c.querySelector('#historialLecturas').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Movimiento</th><th>Placa</th><th>Confianza OCR</th><th>Resultado</th><th>Evidencia</th><th>Revisión</th></tr></thead><tbody>${d.map(e=>`<tr><td>${esc(fecha(e.fecha_hora))}</td><td>${esc(e.tipo_evento)}</td><td>${esc(e.placa_detectada||'SIN LECTURA')}</td><td>${e.confianza_reconocimiento??'-'}%</td><td>${esc(e.resultado_validacion)}</td><td>${e.evidencia_tipo==='IMAGEN_REAL'?'Fotografía registrada':'No verificada'}</td><td>${gestionar&&['INCIERTO','DENEGADO'].includes(e.resultado_validacion)&&!e.autorizado_manual?`<button class="btn revisar" data-id="${e.id}">Revisar</button>`:'-'}</td></tr>`).join('')}</tbody></table></div>`;c.querySelectorAll('.revisar').forEach(b=>b.onclick=async()=>{const placa=prompt('Placa corregida tras examinar la evidencia:');if(!placa)return;const motivo=prompt('Motivo de la revisión (mínimo 10 caracteres):');if(!motivo)return;try{const r=await api('/accesos/eventos/'+b.dataset.id+'/revision-manual',{method:'POST',body:{placa,motivo}});aviso('Revisión registrada: '+r.resultado);await refrescar()}catch(e){aviso(e.message)}})}catch(e){aviso(e.message)}}
 if(gestionar)c.querySelector('#lectura').onsubmit=async ev=>{ev.preventDefault();const f=new FormData(ev.target),file=f.get('imagen');try{if(!file?.size||file.size>1700000||!['image/jpeg','image/png','image/webp'].includes(file.type))throw Error('Utilice JPG, PNG o WebP menor a 1,7 MB.');const img=await new Promise((ok,no)=>{const r=new FileReader();r.onload=()=>ok(r.result);r.onerror=no;r.readAsDataURL(file)});const r=await api('/accesos/registrar-lectura',{method:'POST',body:{imagen:img,tipoEvento:f.get('tipoEvento'),puntoAcceso:f.get('puntoAcceso')}});c.querySelector('#resultadoLectura').textContent=`Resultado: ${r.resultado}. Placa: ${r.placa||'incierta'}. Confianza: ${r.confianza}%. ${r.requiereRevision?'REQUIERE REVISIÓN MANUAL.':''}`;await refrescar()}catch(e){aviso(e.message)}};
 await refrescar();
}
