import {api,fecha,tienePermiso,aviso} from '../api.js';
const h=v=>String(v??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
let timer=null;let filtro='';let contenedor=null;
export async function renderAlertas(c){
 if(timer)clearInterval(timer);contenedor=c;filtro='';
 c.innerHTML=`<div class="page-head"><div><h1>Alertas y notificaciones</h1><p>Incidentes de capacidad, cámaras y consistencia, con trazabilidad del responsable.</p></div></div><div class="card panel"><label for="filtroAlertas">Filtrar estado</label> <select id="filtroAlertas"><option value="">Todas</option><option value="ABIERTA">Abiertas</option><option value="ATENDIDA">Atendidas</option><option value="CERRADA">Cerradas</option></select> <button type="button" id="recargarAlertas">Actualizar</button> ${tienePermiso('alertas.gestionar')?'<button type="button" id="inspeccionarAlertas">Inspeccionar ahora</button>':''}<div id="resumenAlertas" aria-live="polite"></div></div><div id="listaAlertas" aria-live="polite"></div>`;
 c.querySelector('#filtroAlertas').onchange=e=>{filtro=e.target.value;void cargar()};c.querySelector('#recargarAlertas').onclick=()=>void cargar();
 const ins=c.querySelector('#inspeccionarAlertas');if(ins)ins.onclick=async()=>{try{ins.disabled=true;const r=await api('/alertas/inspeccionar',{method:'POST'});aviso(`${r.nuevas||0} alertas nuevas`);await cargar()}catch(e){aviso(e.message)}finally{ins.disabled=false}};
 await cargar();timer=setInterval(()=>{if(contenedor?.isConnected&&contenedor.querySelector('#listaAlertas'))void cargar();else {clearInterval(timer);timer=null}},10000);
}
async function cargar(){if(!contenedor?.querySelector('#listaAlertas'))return;try{
 const [items,resumen]=await Promise.all([api('/alertas'+(filtro?'?estado='+encodeURIComponent(filtro):'')),api('/alertas/resumen')]);
 const indicador=contenedor.querySelector('#resumenAlertas');indicador.textContent=`Abiertas: ${resumen.abiertas} · Prioritarias: ${resumen.prioritarias} · En atención: ${resumen.atendidas} · Cerradas: ${resumen.cerradas}`;
 const lista=contenedor.querySelector('#listaAlertas');lista.innerHTML=items.length?items.map(a=>`<article class="alert-row ${h(a.severidad)}" style="margin:12px 0;padding:15px"><strong>${h(a.titulo)}</strong><div>${h(a.descripcion)}</div><small>${h(a.severidad)} · ${h(a.estado)} · ${fecha(a.abierta_en)} · ${h(a.zona_nombre||a.dispositivo_nombre||'General')}</small><div><small>Responsable: ${h(a.asignado_nombre||'Sin asignar')}${a.cerrado_nombre?' · Cerrada por: '+h(a.cerrado_nombre):''}</small></div><div style="display:flex;gap:8px;flex-wrap:wrap"><button type="button" data-historial="${h(a.id)}">Historial</button>${tienePermiso('alertas.gestionar')&&a.estado!=='CERRADA'?`<button type="button" data-accion="${a.estado==='ABIERTA'?'atender':'cerrar'}" data-id="${h(a.id)}">${a.estado==='ABIERTA'?'Atender':'Cerrar'}</button>`:''}</div><div id="h-${h(a.id)}"></div></article>`).join(''):'<div class="card panel empty">No hay alertas para el filtro seleccionado.</div>';
 lista.querySelectorAll('[data-accion]').forEach(b=>b.onclick=async()=>{const comentario=prompt('Indique el motivo o acción realizada (mínimo 8 caracteres):');if(comentario===null)return;try{b.disabled=true;await api('/alertas/'+b.dataset.id+'/'+b.dataset.accion,{method:'PATCH',body:{comentario}});aviso('Alerta actualizada');await cargar()}catch(e){aviso(e.message);b.disabled=false}});
 lista.querySelectorAll('[data-historial]').forEach(b=>b.onclick=async()=>{try{const r=await api('/alertas/'+b.dataset.historial+'/historial');const destino=contenedor.querySelector('#h-'+b.dataset.historial);destino.innerHTML=r.map(x=>`<p><small>${fecha(x.creado_en)} · ${h(x.accion)} · ${h(x.responsable||'Sistema')} · ${h(x.comentario||'')}</small></p>`).join('')||'Sin historial.'}catch(e){aviso(e.message)}});
 }catch(e){const lista=contenedor.querySelector('#listaAlertas');if(lista)lista.textContent=e.message;}}
