import {api,fecha,aviso} from '../api.js';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
export async function renderAuditoria(c){
 c.innerHTML=`<div class="page-head"><div><h1>Auditoría y seguridad</h1><p>Trazabilidad institucional · consultas para personal autorizado</p></div></div>
 <div class="card panel"><form id="audit-f" class="audit-filters"><label>Desde<input name="desde" type="date"></label><label>Hasta<input name="hasta" type="date"></label><label>Acción<input name="accion" maxlength="90" placeholder="Ej. LOGIN"></label><label>Usuario<input name="usuario" maxlength="100" placeholder="Nombre o cuenta"></label><label>Clasificación<select name="tipo"><option>TODOS</option><option>SEGURIDAD</option><option>ADMINISTRATIVA</option></select></label><button class="btn primary">Consultar</button></form><p id="audit-total" aria-live="polite"></p><div class="table-wrap"><table><thead><tr><th>Fecha / hora</th><th>Usuario</th><th>Acción</th><th>Entidad</th><th>Detalle</th></tr></thead><tbody id="audit-body"></tbody></table></div><div class="audit-pagination"><button class="btn" id="audit-prev" type="button">Anterior</button><span id="audit-page"></span><button class="btn" id="audit-next" type="button">Siguiente</button></div></div>
 <div class="card panel"><h3>Eventos de dispositivos</h3><p>Fallas y transiciones de estado registradas automáticamente.</p><div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Dispositivo</th><th>Evento</th><th>Anterior</th><th>Nuevo</th></tr></thead><tbody id="audit-devices"></tbody></table></div></div>`;
 const form=c.querySelector('#audit-f');let pagina=1,total=0,limite=25;
 async function cargar(){const p=new URLSearchParams(new FormData(form));p.set('pagina',pagina);p.set('limite',limite);const d=await api('/auditoria?'+p);total=d.total;c.querySelector('#audit-total').textContent=`${total} eventos encontrados · orden cronológico descendente`;c.querySelector('#audit-page').textContent=`Página ${pagina} de ${Math.max(1,Math.ceil(total/limite))}`;c.querySelector('#audit-prev').disabled=pagina<=1;c.querySelector('#audit-next').disabled=pagina*limite>=total;c.querySelector('#audit-body').innerHTML=d.registros.length?d.registros.map(x=>`<tr><td>${esc(fecha(x.creado_en))}</td><td>${esc(x.nombre_completo||x.nombre_usuario||'Sistema')}</td><td>${esc(x.accion)}</td><td>${esc(x.entidad)}</td><td><details><summary>Ver registro</summary><pre class="audit-detail">${esc(JSON.stringify(x.detalle||{},null,2))}</pre></details></td></tr>`).join(''):'<tr><td colspan="5">No hay eventos que cumplan los filtros.</td></tr>'}
 async function cargarDispositivos(){const d=await api('/auditoria/dispositivos');c.querySelector('#audit-devices').innerHTML=d.length?d.map(x=>`<tr><td>${esc(fecha(x.creado_en))}</td><td>${esc(x.nombre||x.codigo)}</td><td>${esc(x.tipo_evento)}</td><td>${esc(x.estado_anterior||'-')}</td><td>${esc(x.estado_nuevo||'-')}</td></tr>`).join(''):'<tr><td colspan="5">Sin cambios registrados.</td></tr>'}
 form.onsubmit=e=>{e.preventDefault();pagina=1;cargar().catch(e=>aviso(e.message))};c.querySelector('#audit-prev').onclick=()=>{if(pagina>1){pagina--;cargar().catch(e=>aviso(e.message))}};c.querySelector('#audit-next').onclick=()=>{if(pagina*limite<total){pagina++;cargar().catch(e=>aviso(e.message))}};
 await Promise.all([cargar(),cargarDispositivos()]);
}
