import {api,fecha,aviso} from '../api.js';
const h=v=>String(v??'').replace(/[&<>"']/g,x=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[x]));
const estados=['','AUTORIZADO','DENEGADO','INCIERTO','MANUAL','PENDIENTE'];
let secuencia=0;
export async function renderHistorial(c){
 const token=++secuencia;
 c.innerHTML=`<div class="page-head"><div><h1>Historial y trazabilidad</h1><p>Registro cronológico de ingresos, salidas y cambios de ocupación.</p></div></div><div class="card panel"><div class="history-tabs"><button class="btn primary" id="tab-access">Ingresos y salidas</button><button class="btn" id="tab-occup">Cambios de ocupación</button></div><form id="history-filter" class="history-filters"><label>Placa<input name="placa" maxlength="20" placeholder="Buscar por placa"></label><label>Tipo<select name="tipo"><option value="">Todos</option><option>INGRESO</option><option>SALIDA</option></select></label><label>Estado<select name="estado">${estados.map(x=>`<option value="${x}">${x||'Todos'}</option>`).join('')}</select></label><label>Desde<input name="desde" type="date"></label><label>Hasta<input name="hasta" type="date"></label><button class="btn primary" type="submit">Buscar</button><button class="btn" type="reset">Limpiar</button></form><div id="history-summary" role="status" aria-live="polite"></div><div id="history-results"></div><div class="history-pages"><button class="btn" id="prevPage">Anterior</button><span id="pageLabel"></span><button class="btn" id="nextPage">Siguiente</button></div><div id="history-detail"></div></div>`;
 let page=1,totalPages=1,tab='accesos',busy=false;
 const $=id=>c.querySelector('#'+id);const alive=()=>token===secuencia&&c.isConnected&&!!$('history-results')&&c.dataset.moduloActivo==='historial';
 async function cargar(){if(busy||!alive())return;busy=true;$('history-summary').textContent='Consultando eventos...';try{
  const f=new FormData($('history-filter'));const params=new URLSearchParams({pagina:String(page),limite:'25'});
  for(const key of ['desde','hasta'])if(f.get(key))params.set(key,f.get(key));
  if(tab==='accesos')for(const key of ['placa','tipo','estado'])if(f.get(key))params.set(key,f.get(key));
  if(tab==='ocupacion'&&['LIBRE','OCUPADA','FUERA_SERVICIO','SIN_DATOS'].includes(f.get('estado')))params.set('estado',f.get('estado'));
  const d=await api('/historial/'+tab+'?'+params);if(!alive())return;totalPages=d.paginas;
  $('history-summary').textContent=`${d.total} evento(s) · orden del más reciente al más antiguo`;
  $('pageLabel').textContent=`Página ${d.pagina} de ${d.paginas}`;$('prevPage').disabled=page<=1;$('nextPage').disabled=page>=d.paginas;
  const headers=tab==='accesos'?['Fecha y hora','Placa','Tipo','Resultado','Punto de acceso','Evidencia','Detalle']:['Fecha y hora','Zona','Plaza','Estado anterior','Estado nuevo','Origen','Confianza'];
  const rows=d.items.map(e=>tab==='accesos'?`<tr><td>${h(fecha(e.fecha_hora))}</td><td>${h(e.placa_detectada||'Sin lectura')}</td><td>${h(e.tipo_evento)}</td><td>${h(e.resultado_validacion)}</td><td>${h(e.punto_acceso)}</td><td>${h(e.evidencia_tipo||'No disponible')}</td><td><button class="btn history-detail-btn" data-id="${h(e.id)}">Reconstruir</button></td></tr>`:`<tr><td>${h(fecha(e.cambiado_en))}</td><td>${h(e.zona_nombre)}</td><td>${h(e.plaza_codigo)}</td><td>${h(e.estado_anterior||'Sin datos')}</td><td>${h(e.estado_nuevo)}</td><td>${h(e.origen)}</td><td>${e.confianza==null?'—':h(e.confianza)+'%'}</td></tr>`).join('');
  $('history-results').innerHTML=`<div class="table-wrap"><table><thead><tr>${headers.map(x=>`<th>${x}</th>`).join('')}</tr></thead><tbody>${rows||`<tr><td colspan="${headers.length}">No hay eventos para estos filtros.</td></tr>`}</tbody></table></div>`;
  $('history-results').querySelectorAll('.history-detail-btn').forEach(b=>b.onclick=()=>detalle(b.dataset.id));
 }catch(e){if(alive())$('history-summary').textContent='No se pudo cargar: '+e.message;}finally{busy=false;}}
 async function detalle(id){$('history-detail').innerHTML='<section class="card panel">Cargando reconstrucción...</section>';try{const d=await api('/historial/accesos/'+encodeURIComponent(id));if(!alive())return;const e=d.evento;$('history-detail').innerHTML=`<section class="card panel"><div style="display:flex;justify-content:space-between;gap:12px"><h3>Reconstrucción del evento</h3><button class="btn" id="closeHistoryDetail">Cerrar</button></div><dl class="history-facts">${[['Identificador',e.id],['Fecha y hora',fecha(e.fecha_hora)],['Origen',e.origen],['Movimiento',e.tipo_evento],['Placa detectada',e.placa_detectada||'No detectada'],['Resultado',e.resultado_validacion],['Punto de acceso',e.punto_acceso],['Cámara',e.camara_nombre||'No registrada'],['Confianza OCR',e.confianza_reconocimiento==null?'No disponible':e.confianza_reconocimiento+'%'],['Validación manual',e.autorizado_manual?'Sí':'No'],['Responsable',e.revisor],['Evidencia',e.tiene_evidencia?'Imagen asociada al registro':'No disponible'],['Observaciones',e.observaciones||'Sin observaciones']].map(([k,v])=>`<div><dt>${h(k)}</dt><dd>${h(v)}</dd></div>`).join('')}</dl><h4>Lecturas y revisiones</h4>${d.lecturas.length?`<div class="table-wrap"><table><thead><tr><th>Fecha</th><th>Placa OCR</th><th>Confianza</th><th>Estado</th><th>Corrección</th></tr></thead><tbody>${d.lecturas.map(r=>`<tr><td>${h(fecha(r.creado_en))}</td><td>${h(r.placa_detectada||'—')}</td><td>${h(r.confianza??'—')}</td><td>${h(r.estado_validacion)}</td><td>${h(r.placa_corregida||'—')}</td></tr>`).join('')}</tbody></table></div>`:'<p>No se registraron lecturas adicionales.</p>'}</section>`;$('closeHistoryDetail').onclick=()=>$('history-detail').replaceChildren();}catch(e){aviso(e.message);}}
 $('history-filter').onsubmit=e=>{e.preventDefault();page=1;cargar()};$('history-filter').onreset=()=>{setTimeout(()=>{page=1;cargar()},0)};
 $('tab-access').onclick=()=>switchTab('accesos');$('tab-occup').onclick=()=>switchTab('ocupacion');
 function switchTab(t){tab=t;page=1;$('history-detail').replaceChildren();$('history-filter').reset();$('history-filter').querySelector('[name=placa]').closest('label').hidden=t!=='accesos';$('history-filter').querySelector('[name=tipo]').closest('label').hidden=t!=='accesos';$('history-filter').querySelector('[name=estado]').closest('label').hidden=t!=='accesos';$('tab-access').classList.toggle('primary',t==='accesos');$('tab-occup').classList.toggle('primary',t==='ocupacion');cargar()}
 $('prevPage').onclick=()=>{if(page>1){page--;cargar()}};$('nextPage').onclick=()=>{if(page<totalPages){page++;cargar()}};
 await cargar();
}
