import {api,aviso,sesion} from '../api.js';
const esc = x => String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const opciones=(items,selected='',campo='codigo',rotulo='nombre')=>items.map(x=>`<option value="${esc(x[campo])}" ${x[campo]===selected?'selected':''}>${esc(x[rotulo])}</option>`).join('');
export async function renderUsuarios(c){
 let [usuarios,roles,zonas,permisos]=await Promise.all([api('/usuarios'),api('/usuarios/roles'),api('/usuarios/zonas'),api('/usuarios/permisos')]);
 const administra=sesion.usuario?.permisos?.includes('usuarios.permisos');
 const pintar=()=>{
 c.innerHTML=`<div class="page-head"><div><h1>Usuarios, roles y permisos</h1><p>Gestión de cuentas institucionales y zonas autorizadas.</p></div><button class="btn primary" id="nuevoUsuario" type="button">+ Registrar usuario</button></div>
 <section class="card panel"><h2>Usuarios registrados (${usuarios.length})</h2><div class="table-wrap"><table><thead><tr><th>Usuario</th><th>Nombre</th><th>Rol</th><th>Zona asignada</th><th>Estado</th><th>Acción</th></tr></thead><tbody>${usuarios.map(u=>`<tr><td>${esc(u.nombre_usuario)}</td><td>${esc(u.nombre_completo)}</td><td>${esc(u.rol_nombre)}</td><td>${esc(u.zona_nombre||'Sin asignación')}</td><td><strong>${esc(u.estado)}</strong></td><td><button class="btn edit-user" data-id="${esc(u.id)}">Editar</button> <button class="btn toggle-user" data-id="${esc(u.id)}" ${u.id===sesion.usuario?.id||u.id===sesion.usuario?.sub?'disabled':''}>${u.estado==='ACTIVO'?'Deshabilitar':'Habilitar'}</button></td></tr>`).join('')}</tbody></table></div></section>
 <section class="card panel"><h2>Roles y permisos</h2><p>Los permisos controlan las funcionalidades disponibles para cada rol.</p><div class="table-wrap"><table><thead><tr><th>Rol</th><th>Permisos asignados</th><th>Administración</th></tr></thead><tbody>${roles.map(r=>`<tr><td>${esc(r.nombre)}</td><td>${esc(r.permisos.join(', '))}</td><td>${administra&&r.codigo!=='ADMINISTRADOR_SISTEMA'?`<button class="btn edit-role" data-codigo="${esc(r.codigo)}">Configurar permisos</button>`:'Protegido'}</td></tr>`).join('')}</tbody></table></div></section><div id="editorUsuarios"></div>`;
 c.querySelector('#nuevoUsuario').onclick=()=>editar();c.querySelectorAll('.edit-user').forEach(b=>b.onclick=()=>editar(usuarios.find(x=>x.id===b.dataset.id)));
 c.querySelectorAll('.toggle-user').forEach(b=>b.onclick=async()=>{const u=usuarios.find(x=>x.id===b.dataset.id);if(!confirm(`¿${u.estado==='ACTIVO'?'Deshabilitar':'Habilitar'} a ${u.nombre_completo}?`))return;try{await api('/usuarios/'+u.id,{method:'PATCH',body:{estado:u.estado==='ACTIVO'?'DESHABILITADO':'ACTIVO'}});await cargar();aviso('Estado actualizado.');}catch(e){aviso(e.message)}});
 c.querySelectorAll('.edit-role').forEach(b=>b.onclick=()=>editarPermisos(roles.find(x=>x.codigo===b.dataset.codigo)));
 };
 async function cargar(){[usuarios,roles,zonas,permisos]=await Promise.all([api('/usuarios'),api('/usuarios/roles'),api('/usuarios/zonas'),api('/usuarios/permisos')]);pintar()}
 function editar(u){const zonaOpciones=zonas.filter(x=>x.estado==='ACTIVA'||x.codigo===u?.zona_codigo);const div=c.querySelector('#editorUsuarios');div.innerHTML=`<section class="card panel"><h2>${u?'Modificar':'Registrar'} usuario</h2><form id="formUsuario" class="usuario-form"><label>Usuario<input name="nombreUsuario" required maxlength="60" pattern="[a-zA-Z0-9._-]{3,60}" ${u?'disabled':''} value="${esc(u?.nombre_usuario||'')}"></label><label>Nombre completo<input name="nombreCompleto" required maxlength="170" value="${esc(u?.nombre_completo||'')}"></label><label>Correo<input name="correo" type="email" value="${esc(u?.correo||'')}"></label><label>Área<input name="area" value="${esc(u?.area_institucional||'')}"></label><label>Rol<select name="rolCodigo" required>${opciones(roles.filter(x=>x.activo),u?.rol_codigo)}</select></label><label>Zona de parqueo<select name="zonaCodigo"><option value="">Sin asignar</option>${opciones(zonaOpciones,u?.zona_codigo)}</select></label><label>Contraseña ${u?'(dejar vacío para conservar)':''}<input name="contrasena" type="password" minlength="10" autocomplete="new-password" ${u?'':'required'}></label><div><button class="btn primary" type="submit">Guardar cambios</button> <button class="btn" type="button" id="cancelarEditor">Cancelar</button></div></form><p>Los estudiantes deben tener una zona asignada.</p></section>`;div.scrollIntoView({behavior:'smooth',block:'nearest'});div.querySelector('#cancelarEditor').onclick=()=>div.replaceChildren();div.querySelector('form').onsubmit=async e=>{e.preventDefault();const b=Object.fromEntries(new FormData(e.target));if(u)delete b.nombreUsuario;if(!b.contrasena)delete b.contrasena;try{await api(u?'/usuarios/'+u.id:'/usuarios',{method:u?'PATCH':'POST',body:b});await cargar();aviso('Usuario guardado correctamente.')}catch(err){aviso(err.message)}};
 }
 function editarPermisos(r){const div=c.querySelector('#editorUsuarios');const disponibles=permisos.filter(x=>x.codigo!=='usuarios.permisos');div.innerHTML=`<section class="card panel"><h2>Permisos: ${esc(r.nombre)}</h2><p>Seleccione sólo los permisos que necesita este rol.</p><form id="formPermisos"><div class="permisos-grid">${disponibles.map(x=>`<label class="permiso-opcion"><input type="checkbox" name="permiso" value="${esc(x.codigo)}" ${r.permisos.includes(x.codigo)?'checked':''}><span><strong>${esc(x.codigo)}</strong> — ${esc(x.descripcion)}</span></label>`).join('')}</div><button class="btn primary" type="submit">Guardar permisos</button> <button class="btn" type="button" id="cancelarEditor">Cancelar</button></form></section>`;div.scrollIntoView({behavior:'smooth',block:'nearest'});div.querySelector('#cancelarEditor').onclick=()=>div.replaceChildren();div.querySelector('form').onsubmit=async e=>{e.preventDefault();const elegidos=[...div.querySelectorAll('input[name=permiso]:checked')].map(x=>x.value);if(!confirm('¿Guardar nuevos permisos? Las sesiones activas de ese rol se cerrarán.'))return;try{await api('/usuarios/roles/'+encodeURIComponent(r.codigo)+'/permisos',{method:'PUT',body:{permisos:elegidos}});aviso('Permisos guardados.');await cargar()}catch(err){aviso(err.message)}};
 }
 pintar();
}
