import {api,aviso,tienePermiso,fecha} from '../api.js';
const esc=x=>String(x??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const cats=['MILITAR','CIVIL','ADMINISTRATIVO','ESTUDIANTE','VISITANTE','PROVEEDOR','INSTITUCIONAL'];
const tipos=['AUTOMOVIL','CAMIONETA','MOTOCICLETA','CAMION','MINIBUS','OTRO'];
const opciones=(list,value)=>list.map(v=>`<option value="${v}" ${v===value?'selected':''}>${v}</option>`).join('');
export async function renderVehiculos(c){
 const gestionar=tienePermiso('vehiculos.gestionar'),estado={q:'',categoria:'',filtro:''};let lista=[];
 c.innerHTML=`<div class="page-head"><div><h1>Vehículos y autorizaciones</h1><p>Control institucional de vehículos registrados y permisos de circulación.</p></div>${gestionar?'<button class="btn primary" id="nuevoVeh">+ Registrar vehículo</button>':''}</div><section class="card panel"><h2>Consulta de vehículos</h2><div style="display:flex;flex-wrap:wrap;gap:10px;margin-bottom:15px"><input id="busquedaVeh" placeholder="Buscar por placa" aria-label="Buscar por placa"><select id="categoriaVeh" aria-label="Categoría"><option value="">Todas las categorías</option>${opciones(cats,'')}</select><select id="estadoVeh" aria-label="Estado"><option value="">Todos los estados</option>${opciones(['ACTIVO','SUSPENDIDO','RETIRADO'],'')}</select><button class="btn" id="filtrarVeh">Buscar</button></div><div id="listaVeh"></div></section><div id="editorVeh"></div>`;
 const editor=c.querySelector('#editorVeh');
 async function cargar(){try{lista=await api('/vehiculos?'+new URLSearchParams({q:estado.q,categoria:estado.categoria,estado:estado.filtro}));c.querySelector('#listaVeh').innerHTML=`<div class="table-wrap"><table><thead><tr><th>Placa</th><th>Tipo</th><th>Referencia</th><th>Categoría</th><th>Estado</th><th>Autorización</th><th>Acciones</th></tr></thead><tbody>${lista.map(v=>`<tr><td><strong>${esc(v.placa)}</strong></td><td>${esc(v.tipo_vehiculo)}</td><td>${esc(v.referencia_propietario||'-')}</td><td>${esc(v.categoria_usuario)}</td><td>${esc(v.estado)}</td><td>${esc(v.autorizacion_vigencia)}</td><td><button class="btn historyVeh" data-id="${v.id}">Autorizaciones</button> ${gestionar?`<button class="btn editVeh" data-id="${v.id}">Editar</button> <button class="btn authVeh" data-id="${v.id}">Autorizar</button>`:''}</td></tr>`).join('')}</tbody></table></div>${!lista.length?'<p>No se encontraron vehículos.</p>':''}`;c.querySelectorAll('.historyVeh').forEach(b=>b.onclick=()=>historial(b.dataset.id));c.querySelectorAll('.editVeh').forEach(b=>b.onclick=()=>editar(lista.find(x=>x.id===b.dataset.id)));c.querySelectorAll('.authVeh').forEach(b=>b.onclick=()=>autorizar(lista.find(x=>x.id===b.dataset.id)));}catch(e){aviso(e.message)}}
 function editar(v){editor.innerHTML=`<section class="card panel"><h2>${v?'Editar vehículo':'Registrar vehículo'}</h2><form id="formVeh"><div style="display:grid;grid-template-columns:repeat(auto-fit,minmax(190px,1fr));gap:12px"><label>Placa<input name="placa" required maxlength="20" value="${esc(v?.placa||'')}"></label><label>Tipo<select name="tipoVehiculo">${opciones(tipos,v?.tipo_vehiculo||'AUTOMOVIL')}</select></label><label>Marca<input name="marca" maxlength="80" value="${esc(v?.marca||'')}"></label><label>Modelo<input name="modelo" maxlength="80" value="${esc(v?.modelo||'')}"></label><label>Color<input name="color" maxlength="60" value="${esc(v?.color||'')}"></label><label>Referencia de propietario<input name="referenciaPropietario" maxlength="170" value="${esc(v?.referencia_propietario||'')}"></label><label>Categoría<select name="categoriaUsuario">${opciones(cats,v?.categoria_usuario||'INSTITUCIONAL')}</select></label><label>Estado<select name="estado">${opciones(['ACTIVO','SUSPENDIDO','RETIRADO'],v?.estado||'ACTIVO')}</select></label></div><p><button class="btn primary" type="submit">Guardar vehículo</button> <button class="btn cancelar" type="button">Cancelar</button></p></form></section>`;editor.querySelector('.cancelar').onclick=()=>editor.innerHTML='';editor.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const body=Object.fromEntries(new FormData(ev.target));try{await api(v?'/vehiculos/'+v.id:'/vehiculos',{method:v?'PATCH':'POST',body});editor.innerHTML='';aviso('Vehículo guardado.');await cargar()}catch(e){aviso(e.message)}};editor.scrollIntoView({behavior:'smooth'});}
 function autorizar(v){editor.innerHTML=`<section class="card panel"><h2>Nueva autorización: ${esc(v.placa)}</h2><form id="formAuto"><label>Tipo<select name="tipoAutorizacion">${opciones(['PERMANENTE','TEMPORAL','EXCEPCIONAL'],'TEMPORAL')}</select></label><label>Válida desde<input type="datetime-local" name="validoDesde" required></label><label>Válida hasta (obligatoria en temporal y excepcional)<input type="datetime-local" name="validoHasta"></label><label>Motivo<input name="motivo" maxlength="1000" placeholder="Motivo o referencia institucional"></label><p><button class="btn primary" type="submit">Registrar autorización</button> <button class="btn cancelar" type="button">Cancelar</button></p></form></section>`;editor.querySelector('.cancelar').onclick=()=>editor.innerHTML='';editor.querySelector('[name=validoDesde]').value=new Date(Date.now()-new Date().getTimezoneOffset()*60000).toISOString().slice(0,16);editor.querySelector('form').onsubmit=async ev=>{ev.preventDefault();const body=Object.fromEntries(new FormData(ev.target));try{await api(`/vehiculos/${v.id}/autorizaciones`,{method:'POST',body:{...body,validoDesde:new Date(body.validoDesde).toISOString(),validoHasta:body.validoHasta?new Date(body.validoHasta).toISOString():null}});editor.innerHTML='';aviso('Autorización registrada.');await cargar()}catch(e){aviso(e.message)}};editor.scrollIntoView({behavior:'smooth'});}
 async function historial(id){try{const v=lista.find(x=>x.id===id),items=await api(`/vehiculos/${id}/autorizaciones`);editor.innerHTML=`<section class="card panel"><h2>Autorizaciones: ${esc(v.placa)}</h2><div class="table-wrap"><table><thead><tr><th>Tipo</th><th>Desde</th><th>Hasta</th><th>Estado</th><th>Motivo</th><th>Acciones</th></tr></thead><tbody>${items.map(a=>`<tr><td>${esc(a.tipo_autorizacion)}</td><td>${esc(fecha(a.valido_desde))}</td><td>${a.valido_hasta?esc(fecha(a.valido_hasta)):'Sin vencimiento'}</td><td>${esc(a.vigencia)}</td><td>${esc(a.motivo||'-')}</td><td>${gestionar&&a.estado==='ACTIVA'?`<button class="btn susp" data-id="${a.id}">Suspender</button> <button class="btn rev" data-id="${a.id}">Revocar</button>`:'-'}</td></tr>`).join('')}</tbody></table></div>${!items.length?'<p>No hay autorizaciones registradas.</p>':''}<button class="btn" id="cerrarHist">Cerrar</button></section>`;editor.querySelector('#cerrarHist').onclick=()=>editor.innerHTML='';for(const [selector,value] of [['.susp','SUSPENDIDA'],['.rev','REVOCADA']])editor.querySelectorAll(selector).forEach(b=>b.onclick=async()=>{const motivo=prompt('Indique el motivo de la modificación:');if(!motivo?.trim())return;try{await api(`/vehiculos/${id}/autorizaciones/${b.dataset.id}`,{method:'PATCH',body:{estado:value,motivo}});aviso('Autorización actualizada.');await cargar();await historial(id)}catch(e){aviso(e.message)}});editor.scrollIntoView({behavior:'smooth'});}catch(e){aviso(e.message)}}
 c.querySelector('#filtrarVeh').onclick=()=>{estado.q=c.querySelector('#busquedaVeh').value.trim();estado.categoria=c.querySelector('#categoriaVeh').value;estado.filtro=c.querySelector('#estadoVeh').value;cargar()};c.querySelector('#busquedaVeh').onkeydown=e=>{if(e.key==='Enter')c.querySelector('#filtrarVeh').click()};if(gestionar)c.querySelector('#nuevoVeh').onclick=()=>editar(null);await cargar();
}
