import { Router } from 'express';
import { query, pool } from '../../config/db.js';
import { authenticate } from '../../middleware/auth.js';
import { asyncHandler } from '../../utils/asyncHandler.js';
import { hashPassword } from '../../utils/security.js';

export const usuariosRouter = Router();
usuariosRouter.use(authenticate);
function puede(req, permiso) { return req.user.permisos.includes(permiso) || req.user.permisos.includes('*'); }
function asegurar(permiso) { return (req,res,next) => puede(req,permiso) ? next() : res.status(403).json({message:'No tiene autorización para esta operación.'}); }
const validoUUID = x => /^[0-9a-f]{8}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{4}-[0-9a-f]{12}$/i.test(x || '');
const estados = new Set(['ACTIVO','DESHABILITADO']);
const auditoria = async (cl,req,accion,entidad,id,antes,despues) => cl.query(`INSERT INTO auditoria(usuario_id,accion,entidad,entidad_id,detalle,direccion_ip,agente_usuario) VALUES($1,$2,$3,$4,$5,$6,$7)`,[req.user.sub,accion,entidad,id,JSON.stringify({antes,despues}),req.ip,req.headers['user-agent']?.slice(0,500)||null]);
const error = (res,codigo,mensaje)=>res.status(codigo).json({message:mensaje});

usuariosRouter.get('/roles',asegurar('usuarios.gestionar'),asyncHandler(async(req,res)=>{const r=await query(`SELECT r.id,r.codigo,r.nombre,r.descripcion,r.activo,COALESCE(array_agg(p.codigo ORDER BY p.codigo) FILTER(WHERE p.codigo IS NOT NULL),'{}') permisos FROM roles r LEFT JOIN roles_permisos rp ON rp.rol_id=r.id LEFT JOIN permisos p ON p.id=rp.permiso_id GROUP BY r.id ORDER BY r.nombre`);res.json(r.rows)}));
usuariosRouter.get('/permisos',asegurar('usuarios.gestionar'),asyncHandler(async(req,res)=>{res.json((await query('SELECT id,codigo,modulo,descripcion FROM permisos ORDER BY modulo,codigo')).rows)}));
usuariosRouter.get('/zonas',asegurar('usuarios.gestionar'),asyncHandler(async(req,res)=>res.json((await query("SELECT id,codigo,nombre,tipo_zona,estado FROM zonas_parqueo ORDER BY nombre")).rows)));
usuariosRouter.get('/',asegurar('usuarios.gestionar'),asyncHandler(async(req,res)=>res.json((await query(`SELECT u.id,u.nombre_usuario,u.nombre_completo,u.correo,u.area_institucional,u.estado,u.ultimo_ingreso_en,u.creado_en,r.codigo rol_codigo,r.nombre rol_nombre,z.codigo zona_codigo,z.nombre zona_nombre FROM usuarios u JOIN roles r ON r.id=u.rol_id LEFT JOIN zonas_parqueo z ON z.id=u.zona_asignada_id ORDER BY u.nombre_completo`)).rows)));

async function verificarRolZona(cl,rolCodigo,zonaCodigo){
 const r=await cl.query('SELECT id,codigo FROM roles WHERE codigo=$1 AND activo=TRUE',[rolCodigo]);if(!r.rowCount)throw Object.assign(new Error('Seleccione un rol activo válido.'),{status:400});
 let zonaId=null;
 if(zonaCodigo){const z=await cl.query('SELECT id FROM zonas_parqueo WHERE codigo=$1 AND estado=$2',[zonaCodigo,'ACTIVA']);if(!z.rowCount)throw Object.assign(new Error('La zona seleccionada no está disponible.'),{status:400});zonaId=z.rows[0].id;}
 if(rolCodigo==='ESTUDIANTE'&&!zonaId)throw Object.assign(new Error('Debe asignar una zona de parqueo al estudiante.'),{status:400});
 return {rolId:r.rows[0].id,zonaId};
}
function validarUsuario(b,nuevo){if(nuevo&&(!b.nombreUsuario||!b.contrasena||!b.nombreCompleto||!b.rolCodigo))return 'Complete los campos obligatorios.';if(b.nombreUsuario!==undefined&&!/^[a-zA-Z0-9._-]{3,60}$/.test(b.nombreUsuario))return 'El nombre de usuario debe tener entre 3 y 60 caracteres y no incluir espacios.';if(b.contrasena!==undefined&&b.contrasena!==''&&b.contrasena.length<10)return 'La contraseña debe tener al menos 10 caracteres.';if(b.nombreCompleto!==undefined&&(!b.nombreCompleto.trim()||b.nombreCompleto.length>170))return 'Ingrese un nombre completo válido.';if(b.correo&& !/^[^\s@]+@[^\s@]+\.[^\s@]+$/.test(b.correo))return 'Correo no válido.';if(b.estado!==undefined&&!estados.has(b.estado))return 'Estado no válido.';return null;}
usuariosRouter.post('/',asegurar('usuarios.gestionar'),asyncHandler(async(req,res)=>{const b=req.body;const e=validarUsuario(b,true);if(e)return error(res,400,e);const cl=await pool.connect();try{await cl.query('BEGIN');if(b.rolCodigo==='ADMINISTRADOR_SISTEMA'&&!puede(req,'usuarios.permisos')){await cl.query('ROLLBACK');return error(res,403,'No está autorizado para asignar el rol administrador.');}const {rolId,zonaId}=await verificarRolZona(cl,b.rolCodigo,b.zonaCodigo);const r=await cl.query(`INSERT INTO usuarios(nombre_usuario,hash_contrasena,nombre_completo,correo,area_institucional,rol_id,zona_asignada_id) VALUES($1,$2,$3,$4,$5,$6,$7) RETURNING id,nombre_usuario,nombre_completo,correo,area_institucional,estado`,[b.nombreUsuario.trim(),hashPassword(b.contrasena),b.nombreCompleto.trim(),b.correo||null,b.area||null,rolId,zonaId]);await auditoria(cl,req,'USUARIO_CREAR','usuarios',r.rows[0].id,null,{usuario:b.nombreUsuario,rol:b.rolCodigo,zona:b.zonaCodigo||null});await cl.query('COMMIT');res.status(201).json(r.rows[0]);}catch(e){await cl.query('ROLLBACK');if(e.code==='23505')return error(res,409,'El nombre de usuario ya está registrado.');throw e;}finally{cl.release()}}));
usuariosRouter.patch('/:id',asegurar('usuarios.gestionar'),asyncHandler(async(req,res)=>{if(!validoUUID(req.params.id))return error(res,400,'Identificador inválido.');const b=req.body;const e=validarUsuario(b,false);if(e)return error(res,400,e);const cl=await pool.connect();try{await cl.query('BEGIN');const old=(await cl.query('SELECT u.*,r.codigo rol_codigo,z.codigo zona_codigo FROM usuarios u JOIN roles r ON u.rol_id=r.id LEFT JOIN zonas_parqueo z ON z.id=u.zona_asignada_id WHERE u.id=$1 FOR UPDATE OF u',[req.params.id])).rows[0];if(!old){await cl.query('ROLLBACK');return error(res,404,'Usuario no encontrado.');}const nuevoRol=b.rolCodigo??old.rol_codigo;if((nuevoRol==='ADMINISTRADOR_SISTEMA'||old.rol_codigo==='ADMINISTRADOR_SISTEMA')&&!puede(req,'usuarios.permisos')){await cl.query('ROLLBACK');return error(res,403,'No está autorizado para modificar cuentas administradoras.');}const nuevaZona=b.zonaCodigo!==undefined?b.zonaCodigo:old.zona_codigo;const {rolId,zonaId}=await verificarRolZona(cl,nuevoRol,nuevaZona);const estado=b.estado??old.estado;if(!estados.has(estado)){await cl.query('ROLLBACK');return error(res,400,'Estado inválido.');}if(String(old.id)===String(req.user.sub)&&(estado!=='ACTIVO'||nuevoRol!==old.rol_codigo)){await cl.query('ROLLBACK');return error(res,409,'No puede deshabilitar su propia cuenta ni cambiar su propio rol.');}const r=await cl.query(`UPDATE usuarios SET nombre_completo=$2,correo=$3,area_institucional=$4,rol_id=$5,zona_asignada_id=$6,estado=$7,hash_contrasena=$8,actualizado_en=NOW() WHERE id=$1 RETURNING id,nombre_usuario,nombre_completo,correo,area_institucional,estado`,[old.id,b.nombreCompleto??old.nombre_completo,b.correo!==undefined?(b.correo||null):old.correo,b.area!==undefined?(b.area||null):old.area_institucional,rolId,zonaId,estado,b.contrasena?hashPassword(b.contrasena):old.hash_contrasena]);if(estado!=='ACTIVO'||nuevoRol!==old.rol_codigo||b.contrasena)await cl.query('UPDATE sesiones_autenticacion SET revocado_en=NOW() WHERE usuario_id=$1 AND revocado_en IS NULL',[old.id]);await auditoria(cl,req,'USUARIO_MODIFICAR','usuarios',old.id,{rol:old.rol_codigo,zona:old.zona_codigo,estado:old.estado,nombre:old.nombre_completo},{rol:nuevoRol,zona:nuevaZona,estado,nombre:r.rows[0].nombre_completo,contrasenaCambiada:Boolean(b.contrasena)});await cl.query('COMMIT');res.json(r.rows[0]);}catch(e){await cl.query('ROLLBACK');throw e;}finally{cl.release()}}));

// Solo administradores con autorización explícita pueden administrar privilegios o roles.
usuariosRouter.put('/roles/:codigo/permisos',asegurar('usuarios.permisos'),asyncHandler(async(req,res)=>{const cod=req.params.codigo;const perms=req.body?.permisos;if(!Array.isArray(perms)||perms.some(p=>typeof p!=='string')||new Set(perms).size!==perms.length)return error(res,400,'Seleccione un conjunto válido de permisos.');if(cod==='ADMINISTRADOR_SISTEMA')return error(res,403,'Los permisos del administrador principal están protegidos.');if(perms.includes('usuarios.permisos'))return error(res,403,'No puede delegarse la administración de permisos desde este módulo.');const cl=await pool.connect();try{await cl.query('BEGIN');const r=(await cl.query('SELECT id FROM roles WHERE codigo=$1 AND activo=TRUE FOR UPDATE',[cod])).rows[0];if(!r){await cl.query('ROLLBACK');return error(res,404,'Rol no encontrado.');}const existentes=(await cl.query('SELECT p.codigo FROM roles_permisos rp JOIN permisos p ON p.id=rp.permiso_id WHERE rp.rol_id=$1',[r.id])).rows.map(x=>x.codigo);const validos=(await cl.query('SELECT codigo FROM permisos WHERE codigo=ANY($1::text[])',[perms])).rows.map(x=>x.codigo);if(validos.length!==perms.length){await cl.query('ROLLBACK');return error(res,400,'Se detectaron permisos desconocidos.');}await cl.query('DELETE FROM roles_permisos WHERE rol_id=$1',[r.id]);if(perms.length)await cl.query('INSERT INTO roles_permisos(rol_id,permiso_id) SELECT $1,id FROM permisos WHERE codigo=ANY($2::text[])',[r.id,perms]);await cl.query(`UPDATE sesiones_autenticacion SET revocado_en=NOW() WHERE usuario_id IN (SELECT id FROM usuarios WHERE rol_id=$1) AND revocado_en IS NULL`,[r.id]);await auditoria(cl,req,'ROL_PERMISOS_MODIFICAR','roles',r.id,{permisos:existentes},{permisos:perms});await cl.query('COMMIT');res.json({message:'Permisos actualizados. Los usuarios del rol deben iniciar sesión nuevamente.',codigo:cod,permisos:perms});}catch(e){await cl.query('ROLLBACK');throw e;}finally{cl.release()}}));
